# Generated by Django 4.1.3 on 2023-09-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_connnection_access_token_connnection_expires_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connnection',
            old_name='token_id',
            new_name='id_token',
        ),
        migrations.AlterField(
            model_name='connnection',
            name='token_type',
            field=models.CharField(choices=[('Bearer', 'Bearer')], default='Bearer', max_length=50),
        ),
    ]
