# Generated by Django 4.1.3 on 2024-01-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='url',
            new_name='google_sheet_url',
        ),
    ]
