# Generated by Django 5.1.4 on 2025-09-11 13:20

import endpoints.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_uuid', models.UUIDField(default=uuid.UUID('27955778-12d7-40fc-b55a-99964177a6dc'), unique=True)),
                ('endpoint', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('public_key', models.CharField(blank=True, help_text='Public key allows external users to run operations on the data of authorized database (create, update, delete...)', max_length=100, null=True)),
                ('bearer_token', models.CharField(blank=True, help_text='Bearer token allows external users to authenticate their requests', max_length=200, null=True)),
                ('methods', models.CharField(max_length=10, validators=[endpoints.validators.validate_http_method])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecretApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_uuid', models.UUIDField(default=uuid.UUID('27955778-12d7-40fc-b55a-99964177a6dc'), unique=True)),
                ('endpoint', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('secret_key', models.CharField(blank=True, help_text='Secret key allows the database creator to run internal operations on his databases (create, delete...) or modify instance parameters and should never be shared', max_length=100, null=True)),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
