# Generated by Django 6.0.8 on 2026-08-16 07:39

import django.db.models.deletion
import endpoints.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbschemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('endpoint', models.CharField(blank=True, help_text='A custom name for the endpoint that can be used in the url to access it.', max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('public_key', models.CharField(blank=True, help_text='Public key allows external users to run operations on the data of authorized database (create, update, delete...)', max_length=100, null=True)),
                ('bearer_token', models.CharField(blank=True, help_text='Bearer token allows external users to authenticate their requests', max_length=200, null=True)),
                ('methods', models.JSONField(default=list, validators=[endpoints.validators.validate_http_method])),
                ('database_schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbschemas.databaseschema')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecretApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('endpoint', models.CharField(blank=True, help_text='A custom name for the endpoint that can be used in the url to access it.', max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('secret_key', models.CharField(blank=True, help_text='Secret key allows the database creator to run internal operations on his databases (create, delete...) or modify instance parameters and should never be shared', max_length=100, null=True)),
                ('private', models.BooleanField(default=False)),
                ('database_schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbschemas.databaseschema')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
