# Generated by Django 5.1.4 on 2025-09-11 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbschemas', '0002_alter_databaseschema_options'),
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicapiendpoint',
            name='database_schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbschemas.databaseschema'),
        ),
        migrations.AddField(
            model_name='secretapiendpoint',
            name='database_schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbschemas.databaseschema'),
        ),
        migrations.AlterField(
            model_name='publicapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('2579dafa-cc0c-466c-9c85-1c490faada84'), unique=True),
        ),
        migrations.AlterField(
            model_name='secretapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('2579dafa-cc0c-466c-9c85-1c490faada84'), unique=True),
        ),
    ]
