# Generated by Django 5.1.4 on 2025-09-12 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_alter_publicapiendpoint_endpoint_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('189560dd-2af6-48fa-9b85-b18f321a352a'), unique=True),
        ),
        migrations.AlterField(
            model_name='secretapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('189560dd-2af6-48fa-9b85-b18f321a352a'), unique=True),
        ),
    ]
