# Generated by Django 5.1.4 on 2025-09-12 17:11

import endpoints.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_alter_publicapiendpoint_endpoint_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('f96a9544-31a1-4e6f-b308-3406cad18ee6'), unique=True),
        ),
        migrations.AlterField(
            model_name='publicapiendpoint',
            name='methods',
            field=models.JSONField(default=list, validators=[endpoints.validators.validate_http_method]),
        ),
        migrations.AlterField(
            model_name='secretapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('f96a9544-31a1-4e6f-b308-3406cad18ee6'), unique=True),
        ),
    ]
