# Generated by Django 5.1.4 on 2025-09-13 16:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0008_alter_publicapiendpoint_endpoint_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('da4fbbc4-1a32-4bdf-b314-e1155e3a7cbd'), unique=True),
        ),
        migrations.AlterField(
            model_name='secretapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('da4fbbc4-1a32-4bdf-b314-e1155e3a7cbd'), unique=True),
        ),
    ]
