# Generated by Django 6.0.8 on 2026-08-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0010_alter_publicapiendpoint_endpoint_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicapiendpoint',
            name='endpoint',
            field=models.CharField(blank=True, help_text='A custom name for the endpoint that can be used in the url to access it.', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='secretapiendpoint',
            name='endpoint',
            field=models.CharField(blank=True, help_text='A custom name for the endpoint that can be used in the url to access it.', max_length=200, null=True, unique=True),
        ),
    ]
