# Generated by Django 6.0.8 on 2026-08-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('database_functions', models.JSONField(blank=True, default=list, null=True)),
                ('database_triggers', models.JSONField(blank=True, default=list, null=True)),
                ('document_relationships', models.JSONField(blank=True, default=list, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('paused', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'database schema',
            },
        ),
        migrations.CreateModel(
            name='DatabaseProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheet_api_key', models.CharField(blank=True, help_text='API key for accessing a public Google Sheet', max_length=255, null=True)),
                ('google_sheet_credentials', models.JSONField(blank=True, default=dict, help_text='Credentials for accessing a private Google Sheet', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database_schema', models.ForeignKey(help_text='The database schema that owns this provider', on_delete=django.db.models.deletion.CASCADE, to='dbschemas.databaseschema')),
            ],
            options={
                'verbose_name': 'database provider',
            },
        ),
    ]
