# Generated by Django 5.1.4 on 2025-08-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbschemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaseschema',
            options={'verbose_name': 'database schema'},
        ),
    ]
