# Generated by Django 5.1.4 on 2025-09-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbschemas', '0003_databaseschema_database_functions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseschema',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
