# Generated by Django 5.1.4 on 2025-09-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbschemas', '0005_databaseprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseprovider',
            name='google_sheet_credentials',
            field=models.JSONField(blank=True, default=dict, help_text='Credentials for accessing a private Google Sheet', null=True),
        ),
    ]
