# Generated by Django 6.0.3 on 2026-03-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbschemas', '0006_databaseprovider_google_sheet_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseschema',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databaseschema',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
