# Generated by Django 5.1.4 on 2025-07-18 10:01

import django.db.models.deletion
import slidesbackend.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('block_id', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[slidesbackend.validators.validate_id])),
                ('component', models.CharField(choices=[('table-block', 'Table Block'), ('graph-block', 'Graph Block'), ('grid-block', 'Grid Block'), ('chart-block', 'Chart Block')], default='table-block', max_length=100)),
                ('record_creation_columns', models.JSONField(blank=True, help_text='Columns to consider when creating a new record', null=True)),
                ('record_update_columns', models.JSONField(blank=True, help_text='Columns to consider when updating a new record', null=True)),
                ('visible_columns', models.JSONField(blank=True, help_text='Columns to be visible at the block level', null=True)),
                ('block_data_source', models.URLField(blank=True, help_text='Block level data source', null=True)),
                ('search_columns', models.JSONField(blank=True, help_text='The columns to use for searching data', null=True)),
                ('user_filters', models.JSONField(blank=True, help_text='The filters the user is allowed to use', null=True)),
                ('conditions', models.JSONField(blank=True, help_text='Internal block configuration', null=True)),
                ('allow_record_creation', models.BooleanField(default=True, help_text='Whether the block should accept record creation')),
                ('allow_record_update', models.BooleanField(default=True, help_text='Whether the block should accept record update')),
                ('allow_record_search', models.BooleanField(default=True, help_text='Whether the block should accept record search')),
                ('active', models.BooleanField(default=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slide_id', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[slidesbackend.validators.validate_id])),
                ('slide_data_source', models.CharField(blank=True, help_text='Top level slide data source', max_length=100, null=True)),
                ('access', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('blocks', models.ManyToManyField(blank=True, to='slides.block')),
                ('sheets', models.ManyToManyField(blank=True, to='sheets.sheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
