POST http://127.0.0.1:8000/v1/endpoints/public/50/table/23/my-endpoint
Content-Type: application/json
X-TABLE-TOKEN: lDN2pClGvbcwniFEyRLVAqeXn21Kc3za

{
    "firstname": "John",
    "lastname": "Doe"
}

# GET http://127.0.0.1:8000/v1/endpoints/public/50/table/23/my-endpoint
# Accept: application/json
# X-TABLE-TOKEN: lDN2pClGvbcwniFEyRLVAqeXn21Kc3za
