# Generated by Django 5.1.4 on 2025-08-25 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabledocuments', '0002_rename_uploaded_at_tabledocument_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('component', models.CharField(choices=[('data-table', 'Data Table'), ('graph-table', 'Graph Table')], default='data-table', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('databaase_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbschemas.databaseschema')),
                ('documents', models.ManyToManyField(blank=True, to='tabledocuments.tabledocument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'database_schema'), name='unique_table_name_per_schema')],
            },
        ),
    ]
