# Generated by Django 5.1.4 on 2025-08-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbschemas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databasetable',
            old_name='databaase_schema',
            new_name='database_schema',
        ),
    ]
