# Generated by Django 5.1.4 on 2025-09-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbschemas', '0002_alter_databaseschema_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseschema',
            name='database_functions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='databaseschema',
            name='database_triggers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='databaseschema',
            name='document_relationships',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
