# Generated by Django 5.1.4 on 2025-09-13 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbschemas', '0004_databaseschema_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheet_api_key', models.CharField(blank=True, help_text='API key for accessing a public Google Sheet', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database_schema', models.ForeignKey(help_text='The database schema that owns this provider', on_delete=django.db.models.deletion.CASCADE, to='dbschemas.databaseschema')),
            ],
            options={
                'verbose_name': 'database provider',
            },
        ),
    ]
