OPENDATASOFT_URL = 'https://data.opendatasoft.com/api/explore/v2.1/catalog/datasets/panneaux4x3-feuille1@issy-les-moulineaux/records?limit=5'

OPENDATASOFT_COLUMN_TYPES = [
    {
        'name': 'numero',
        'newName': 'numero',
        'columnType': 'String',
        'unique': False,
        'nullable': True,
        'visible': True,
    },
    {
        'name': 'etat',
        'newName': 'etat',
        'columnType': 'String',
        'unique': False,
        'nullable': True,
        'visible': True,
    },
    {
        'name': 'date_de_1er_montage',
        'newName': 'date_de_1er_montage',
        'columnType': 'String',
        'unique': False,
        'nullable': True,
        'visible': True,
    },
    {
        'name': 'type_panneau',
        'newName': 'type_panneau',
        'columnType': 'String',
        'unique': False,
        'nullable': True,
        'visible': True,
    },
    {
        'name': 'affichage',
        'newName': 'affichage',
        'columnType': 'String',
        'unique': False,
        'nullable': True,
        'visible': True,
    },
    {
        'name': 'adresse_emplacement',
        'newName': 'adresse_emplacement',
        'columnType': 'String',
        'unique': False,
        'nullable': True,
        'visible': True,
    },
    {
        'name': 'details_emplacements',
        'newName': 'details_emplacements',
        'columnType': 'String',
        'unique': False,
        'nullable': True,
        'visible': True,
    },
    {
        'name': 'code_postal',
        'newName': 'code_postal',
        'columnType': 'String',
        'unique': False,
        'nullable': True,
        'visible': True,
    },
    {
        'name': 'commune',
        'newName': 'commune',
        'columnType': 'String',
        'unique': False,
        'nullable': True,
        'visible': True,
    },
    {
        'name': 'coordonnees_gps',
        'newName': 'coordonnees_gps',
        'columnType': 'String',
        'unique': False,
        'nullable': True,
        'visible': True,
    },
    {
        'name': 'street_view',
        'newName': 'street_view',
        'columnType': 'String',
        'unique': False,
        'nullable': True,
        'visible': True,
    }
]
