# Generated by Django 4.1.3 on 2023-12-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_alter_slide_privacy_alter_slide_slide_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
    ]
