# Generated by Django 4.1.3 on 2023-12-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0003_alter_slide_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='visible',
        ),
        migrations.AlterField(
            model_name='slide',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
    ]
