# Generated by Django 4.1.3 on 2023-12-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0004_remove_slide_visible_alter_slide_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='privacy',
        ),
        migrations.AddField(
            model_name='slide',
            name='access',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
    ]
