# Generated by Django 4.1.3 on 2023-12-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0006_alter_slide_access_alter_slide_slide_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='access',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_data_source',
            field=models.CharField(blank=True, help_text='Top level slide data source', max_length=100, null=True),
        ),
    ]
