# Generated by Django 4.1.3 on 2023-12-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0008_block_alter_slide_access_alter_slide_blocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='block_url_source',
            new_name='block_data_source',
        ),
        migrations.AlterField(
            model_name='block',
            name='component',
            field=models.CharField(choices=[('table-block', 'Table Block'), ('graph-block', 'Graph Block'), ('grid-block', 'Grid Block'), ('chart-block', 'Chart Block')], default='table-block', max_length=100),
        ),
        migrations.AlterField(
            model_name='slide',
            name='access',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
    ]
