# Generated by Django 4.1.3 on 2023-12-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0009_rename_block_url_source_block_block_data_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='record_creation_fields',
            new_name='record_creation_columns',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='record_update_fields',
            new_name='record_update_columns',
        ),
        migrations.AlterField(
            model_name='block',
            name='component',
            field=models.CharField(choices=[('table-block', 'Table Block'), ('graph-block', 'Graph Block'), ('grid-block', 'Grid Block'), ('chart-block', 'Chart Block')], default='table-block', max_length=100),
        ),
        migrations.AlterField(
            model_name='slide',
            name='access',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
    ]
