# Generated by Django 4.1.3 on 2023-12-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0010_rename_record_creation_fields_block_record_creation_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='allow_record_creation',
            field=models.BooleanField(default=True, help_text='Whether the block should accept record creation'),
        ),
        migrations.AddField(
            model_name='block',
            name='allow_record_search',
            field=models.BooleanField(default=True, help_text='Whether the block should accept record search'),
        ),
        migrations.AddField(
            model_name='block',
            name='allow_record_update',
            field=models.BooleanField(default=True, help_text='Whether the block should accept record update'),
        ),
        migrations.AlterField(
            model_name='block',
            name='component',
            field=models.CharField(choices=[('table-block', 'Table Block'), ('graph-block', 'Graph Block'), ('grid-block', 'Grid Block'), ('chart-block', 'Chart Block')], default='table-block', max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='record_creation_columns',
            field=models.JSONField(blank=True, help_text='Columns to consider when creating a new record', null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='record_update_columns',
            field=models.JSONField(blank=True, help_text='Columns to consider when updating a new record', null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='access',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
    ]
