# Generated by Django 4.1.3 on 2023-12-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0011_block_allow_record_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='visible_columns',
            field=models.JSONField(blank=True, help_text='Columns to be visible at the block level', null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='component',
            field=models.CharField(choices=[('table-block', 'Table Block'), ('graph-block', 'Graph Block'), ('grid-block', 'Grid Block'), ('chart-block', 'Chart Block')], default='table-block', max_length=100),
        ),
        migrations.AlterField(
            model_name='slide',
            name='access',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
    ]
