# Generated by Django 4.1.3 on 2023-11-04 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sheets.utils
import sheets.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sheet_id', models.CharField(max_length=100, unique=True,
                 validators=[sheets.validators.validate_id])),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('file', models.FileField(help_text='Uses a CSV file to create a new spreadsheet',
                 upload_to=sheets.utils.create_file_name)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
