# Generated by Django 4.1.3 on 2023-11-04 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sheets.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheets', '0002_rename_file_sheet_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheet_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[sheets.validators.validate_id]),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('page_id', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[sheets.validators.validate_id])),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sheets', models.ManyToManyField(blank=True, to='sheets.sheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
