# Generated by Django 4.1.3 on 2023-11-04 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_alter_sheet_sheet_id_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('usage', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sheet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.sheet')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='webhook',
            constraint=models.UniqueConstraint(fields=('webhook_id', 'sheet'), name='unique_webhook_id'),
        ),
    ]
