# Generated by Django 4.1.3 on 2023-11-04 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_webhook_last_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='last_usage',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
