# Generated by Django 4.1.3 on 2023-11-05 12:18

from django.db import migrations, models
import sheets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_alter_webhook_last_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('block_id', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[sheets.validators.validate_id])),
                ('component', models.CharField(choices=[('table-block', 'Table Block'), ('graph-block', 'Graph Block'), ('grid-block', 'Grid Block')], default='table-block', max_length=100)),
                ('allow_record_creation', models.BooleanField(default=True)),
                ('allow_record_updates', models.BooleanField(default=False)),
                ('block_url_source', models.URLField(blank=True, help_text='Block level data source', null=True)),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='page_url_source',
            field=models.URLField(blank=True, help_text='Top level page data source', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='webhook_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[sheets.validators.validate_id]),
        ),
        migrations.AddField(
            model_name='page',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='sheets.block'),
        ),
    ]
