# Generated by Django 4.1.3 on 2023-11-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0007_block_page_page_url_source_page_privacy_page_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='component',
            field=models.CharField(choices=[('table-block', 'Table Block'), ('graph-block', 'Graph Block'), ('grid-block', 'Grid Block')], default='table-block', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_url_source',
            field=models.CharField(blank=True, help_text='Top level page data source', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
    ]
