# Generated by Django 4.1.3 on 2023-11-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_alter_block_component_alter_page_page_url_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='is_endpoint',
            field=models.BooleanField(default=False, help_text='Mark True if the url is an API endpoint'),
        ),
        migrations.AlterField(
            model_name='block',
            name='component',
            field=models.CharField(choices=[('table-block', 'Table Block'), ('graph-block', 'Graph Block'), ('grid-block', 'Grid Block'), ('chart-block', 'Chart Block')], default='table-block', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
    ]
