# Generated by Django 4.1.3 on 2023-11-30 18:05

from django.db import migrations, models
import sheets.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0010_sheet_endpoint_data_key_alter_block_component_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='is_endpoint',
        ),
        migrations.AddField(
            model_name='sheet',
            name='endpoint_url',
            field=models.URLField(blank=True, help_text='The endpoint to use to create a new sheet', null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='component',
            field=models.CharField(choices=[('table-block', 'Table Block'), ('graph-block', 'Graph Block'), ('grid-block', 'Grid Block'), ('chart-block', 'Chart Block')], default='table-block', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='csv_file',
            field=models.FileField(help_text='The csv file to use to create a new sheet', upload_to=sheets.utils.create_file_name),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='url',
            field=models.URLField(blank=True, help_text="The Google sheet's url", null=True, unique=True),
        ),
    ]
