# Generated by Django 4.1.3 on 2023-12-01 08:56

from django.db import migrations, models
import sheets.utils
import sheets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_remove_sheet_is_endpoint_sheet_endpoint_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='search_columns',
            field=models.JSONField(blank=True, help_text='The columns to use for searching data', null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='user_filters',
            field=models.JSONField(blank=True, help_text='The filters the user is allowed to use', null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='component',
            field=models.CharField(choices=[('table-block', 'Table Block'), ('graph-block', 'Graph Block'), ('grid-block', 'Grid Block'), ('chart-block', 'Chart Block')], default='table-block', max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='conditions',
            field=models.JSONField(blank=True, help_text='Internal block configuration', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='csv_file',
            field=models.FileField(blank=True, help_text='The csv file to use to create a new sheet', null=True, upload_to=sheets.utils.create_file_name, verbose_name='CSV file'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[sheets.validators.validate_id], verbose_name='Sheet ID'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='url',
            field=models.URLField(blank=True, help_text="The Google sheet's url", null=True, unique=True, verbose_name='URL'),
        ),
    ]
