# Generated by Django 4.1.3 on 2023-12-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0014_remove_page_column_types_remove_page_columns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='allow_record_creation',
        ),
        migrations.RemoveField(
            model_name='block',
            name='allow_record_updates',
        ),
        migrations.AddField(
            model_name='block',
            name='record_creation_fields',
            field=models.JSONField(blank=True, help_text='Fields to consider when creating a new record', null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='record_update_fields',
            field=models.JSONField(blank=True, help_text='Fields to consider when updating a new record', null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='component',
            field=models.CharField(choices=[('table-block', 'Table Block'), ('graph-block', 'Graph Block'), ('grid-block', 'Grid Block'), ('chart-block', 'Chart Block')], default='table-block', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
    ]
