# Generated by Django 4.1.3 on 2023-12-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0016_alter_block_component_alter_page_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='component',
            field=models.CharField(choices=[('table-block', 'Table Block'), ('graph-block', 'Graph Block'), ('grid-block', 'Grid Block'), ('chart-block', 'Chart Block')], default='table-block', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100),
        ),
    ]
