# Generated by Django 4.1.3 on 2023-12-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0008_block_alter_slide_access_alter_slide_blocks'),
        ('sheets', '0022_alter_block_component'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
