# Generated by Django 5.1.4 on 2025-07-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0030_alter_connnection_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connnection',
            name='token_type',
            field=models.CharField(choices=[('Bearer', 'Bearer')], default='Bearer', max_length=50),
        ),
    ]
