/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const -: typeof import('dts')['-']
  const .: typeof import('dts')['.']
  const /: typeof import('dts')['/']
  const a: typeof import('dts')['a']
  const c: typeof import('dts')['c']
  const d: typeof import('dts')['d']
  const i: typeof import('dts')['i']
  const m: typeof import('dts')['m']
  const o: typeof import('dts')['o']
  const p: typeof import('dts')['p']
  const r: typeof import('dts')['r']
  const s: typeof import('dts')['s']
  const t: typeof import('dts')['t']
  const u: typeof import('dts')['u']
}
