# Generated by Django 5.1.4 on 2025-07-18 10:01

import django.db.models.deletion
import django.utils.timezone
import sheets.utils
import sheets.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sheet_id', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[sheets.validators.validate_id], verbose_name='Sheet ID')),
                ('url', models.URLField(blank=True, help_text="The Google sheet's url", null=True, unique=True, verbose_name='URL')),
                ('csv_file', models.FileField(blank=True, help_text='The csv file to use to create a new sheet', null=True, upload_to=sheets.utils.create_file_name, verbose_name='CSV file')),
                ('endpoint_url', models.URLField(blank=True, help_text='The endpoint to use to create a new sheet', null=True)),
                ('endpoint_data_key', models.CharField(blank=True, help_text='The key under which the data is stored', max_length=100, null=True)),
                ('columns', models.JSONField(blank=True, help_text='Available columns in the data source', null=True)),
                ('column_types', models.JSONField(blank=True, help_text='The data type for each column', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[sheets.validators.validate_id])),
                ('usage', models.PositiveIntegerField(default=0)),
                ('last_usage', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sheet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.sheet')),
            ],
            options={
                'ordering': ['-created_on'],
                'constraints': [models.UniqueConstraint(fields=('webhook_id', 'sheet'), name='unique_webhook_id')],
            },
        ),
    ]
