import { library } from '@fortawesome/fontawesome-svg-core'
import { faFacebookF } from '@fortawesome/free-brands-svg-icons'
import { faComment, faThumbsUp, faThumbsDown, faFlag, faShare, faArrowUp, faCircleCheck, faCog, faEllipsisVertical, faPlus, faXmark, faCaretDown, faCaretUp, faFilter, faArrowDown, faSort, faMagnifyingGlass, faTable, faList, faColumns, faEllipsis, faEye, faImage, faStar, faShoppingBag, faHouse, faLink, faCalendar, faChartSimple, faBoltLightning, faTableCellsLarge, faFileCsv, faSave } from '@fortawesome/free-solid-svg-icons'

library.add(faLink)
library.add(faHouse)
library.add(faCog)
library.add(faCircleCheck)
library.add(faTable)
library.add(faCalendar)
library.add(faChartSimple)
library.add(faBoltLightning)

library.add(faArrowUp)
library.add(faArrowUp)
library.add(faArrowDown)
library.add(faComment)
library.add(faColumns)
library.add(faCaretDown)
library.add(faCaretDown)
library.add(faCaretUp)
library.add(faFileCsv)
library.add(faEllipsisVertical)
library.add(faEllipsis)
library.add(faEye)
library.add(faFacebookF)
library.add(faFlag)
library.add(faFilter)
library.add(faImage)
library.add(faThumbsUp)
library.add(faThumbsDown)
library.add(faList)
library.add(faMagnifyingGlass)
library.add(faPlus)
library.add(faShare)
library.add(faSort)
library.add(faTableCellsLarge)
library.add(faSave)
library.add(faStar)
library.add(faShoppingBag)
library.add(faXmark)

// YouTube
// library.add(faFaceLaugh)
// library.add(faHeart)
// library.add(faMessage)
// library.add(faThumbTack)
// library.add(faBell)
// library.add(faBellSlash)
// library.add(faPlay)
// library.add(faPause)
// library.add(faGauge)
// library.add(faVolumeUp)
// library.add(faVolumeHigh)
// library.add(faVolumeLow)
// library.add(faVolumeXmark)
// library.add(faClose)
// library.add(faArrowLeft)
// library.add(faArrowRight)
