# Generated by Django 6.0.8 on 2026-08-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbschemas', '0001_initial'),
        ('tabledocuments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('active_document_datasource', models.UUIDField(blank=True, help_text='The data that this table is expected to return', null=True)),
                ('component', models.CharField(choices=[('data-table', 'Data Table'), ('graph-table', 'Graph Table')], default='data-table', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database_schema', models.ForeignKey(help_text='The database that owns this table', on_delete=django.db.models.deletion.CASCADE, to='dbschemas.databaseschema')),
                ('documents', models.ManyToManyField(blank=True, help_text='The documents associated with this table. A  table can have multiple associations but will only have one active document as a datasource.', to='tabledocuments.tabledocument')),
            ],
            options={
                'verbose_name': 'database table',
                'constraints': [models.UniqueConstraint(fields=('name', 'database_schema'), name='unique_table_name_per_schema')],
            },
        ),
    ]
