# Generated by Django 5.1.4 on 2025-09-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtables', '0003_databasetable_active_document_datasource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasetable',
            name='column_types',
            field=models.JSONField(blank=True, default=dict, help_text='A mapping of column names to their data types. This is used to enforce data types when displaying the table.'),
        ),
    ]
