# Generated by Django 5.1.4 on 2025-09-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbtables', '0004_databasetable_column_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasetable',
            name='column_types',
        ),
    ]
