# Generated by Django 6.0.8 on 2026-08-16 07:39

import tabledocuments.utils.model_utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, help_text='A csv, xls, xlsx, ods or json file.', null=True, upload_to=tabledocuments.utils.model_utils.upload_file_to, validators=[tabledocuments.utils.model_utils.validate_file])),
                ('column_names', models.JSONField(blank=True, default=list, help_text='A mapping of the column names present in the document')),
                ('column_type_options', models.JSONField(blank=True, default=list, help_text='A mapping of column names to their type options e.g. uniqueness, not null, etc...')),
                ('column_options', models.JSONField(blank=True, default=list, help_text='A mapping of column names to their visibility, editability, sortability and searchability for the final table presentation')),
                ('column_types', models.JSONField(blank=True, default=dict, help_text='A mapping of column names to their data types. This is used to enforce data types when displaying the table.')),
                ('url', models.URLField(blank=True, help_text="The url that was used to request the file's content via HTTP", max_length=500, null=True)),
                ('google_sheet_id', models.CharField(blank=True, help_text='The Google Sheet ID if the document was imported from Google Sheets', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('file__isnull', False), ('url__isnull', False), _connector='OR'), name='file_or_url_required')],
            },
        ),
    ]
