# Generated by Django 6.0.8 on 2026-09-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledocument',
            name='column_type_options',
        ),
    ]
