# Generated by Django 5.1.4 on 2025-08-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0002_tabledocument_url_alter_tabledocument_file'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tabledocument',
            constraint=models.CheckConstraint(condition=models.Q(('file__isnull', False), ('url__isnull', False), _connector='OR'), name='file_or_url_required'),
        ),
    ]
