# Generated by Django 5.1.4 on 2025-08-25 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0004_alter_tabledocument_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledocument',
            name='document_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
