# Generated by Django 5.1.4 on 2025-08-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0005_tabledocument_document_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledocument',
            name='name',
            field=models.CharField(default='Celebrity data', max_length=255),
            preserve_default=False,
        ),
    ]
