# Generated by Django 5.1.4 on 2025-09-10 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0006_alter_tabledocument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledocument',
            name='document_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
