# Generated by Django 5.1.4 on 2025-09-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0010_tabledocument_column_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledocument',
            name='google_sheet_id',
            field=models.CharField(blank=True, help_text='The Google Sheet ID if the document was imported from Google Sheets', max_length=255, null=True),
        ),
    ]
