# Generated by Django 6.0.3 on 2026-03-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0011_tabledocument_google_sheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledocument',
            name='column_type_options',
            field=models.JSONField(blank=True, default=dict, help_text='A mapping of column names to their type options e.g. uniqueness, not null, etc...'),
        ),
        migrations.AlterField(
            model_name='tabledocument',
            name='column_options',
            field=models.JSONField(blank=True, default=list, help_text='A mapping of column names to their visibility, editability, sortability and searchability for the final table presentation'),
        ),
    ]
