# Generated by Django 6.0.3 on 2026-03-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0012_tabledocument_column_type_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledocument',
            name='column_type_options',
            field=models.JSONField(blank=True, default=list, help_text='A mapping of column names to their type options e.g. uniqueness, not null, etc...'),
        ),
    ]
