# Generated by Django 6.0.8 on 2026-08-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0013_alter_tabledocument_column_type_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
