# Generated by Django 5.1.4 on 2025-09-12 14:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_publicapiendpoint_database_schema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('faef6e49-3e59-429f-b274-4456ead61ca0'), unique=True),
        ),
        migrations.AlterField(
            model_name='secretapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('faef6e49-3e59-429f-b274-4456ead61ca0'), unique=True),
        ),
    ]
