# Generated by Django 5.1.4 on 2025-09-12 17:08

import endpoints.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_alter_publicapiendpoint_endpoint_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('e5f2b333-bb7f-4dae-a943-1898a313bcea'), unique=True),
        ),
        migrations.AlterField(
            model_name='publicapiendpoint',
            name='methods',
            field=models.JSONField(default=['GET', 'POST', 'PUT', 'DELETE', 'PATCH'], validators=[endpoints.validators.validate_http_method]),
        ),
        migrations.AlterField(
            model_name='secretapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('e5f2b333-bb7f-4dae-a943-1898a313bcea'), unique=True),
        ),
    ]
