# Generated by Django 5.1.4 on 2025-09-13 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_alter_publicapiendpoint_endpoint_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('2ea32e80-ed5b-4afe-8199-330eb00e1468'), unique=True),
        ),
        migrations.AlterField(
            model_name='secretapiendpoint',
            name='endpoint_uuid',
            field=models.UUIDField(default=uuid.UUID('2ea32e80-ed5b-4afe-8199-330eb00e1468'), unique=True),
        ),
    ]
