# Generated by Django 5.1.4 on 2025-08-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databasetable',
            options={'verbose_name': 'database table'},
        ),
        migrations.AlterField(
            model_name='databasetable',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
