# Generated by Django 5.1.4 on 2025-08-26 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbschemas', '0002_alter_databaseschema_options'),
        ('dbtables', '0002_alter_databasetable_options_and_more'),
        ('tabledocuments', '0006_alter_tabledocument_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasetable',
            name='active_document_datasource',
            field=models.UUIDField(blank=True, help_text='The data that this table is expected to return', null=True),
        ),
        migrations.AlterField(
            model_name='databasetable',
            name='database_schema',
            field=models.ForeignKey(help_text='The database that owns this table', on_delete=django.db.models.deletion.CASCADE, to='dbschemas.databaseschema'),
        ),
        migrations.AlterField(
            model_name='databasetable',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='The documents associated with this table. A  table can have multiple associations but will only have one active document as a datasource.', to='tabledocuments.tabledocument'),
        ),
    ]
