# Generated by Django 5.1.4 on 2025-09-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtables', '0005_remove_databasetable_column_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasetable',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
