# Generated by Django 5.1.4 on 2025-08-25 15:29

import tabledocuments.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledocument',
            name='url',
            field=models.URLField(blank=True, help_text="The url that was used to request the file's content via HTTP", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tabledocument',
            name='file',
            field=models.FileField(blank=True, help_text='A csv, xls, xlsx, ods or json file.', null=True, upload_to=tabledocuments.utils.upload_file_to, validators=[tabledocuments.utils.validate_file]),
        ),
    ]
