# Generated by Django 5.1.4 on 2025-08-25 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabledocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='tabledocument',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
