# Generated by Django 5.1.4 on 2025-08-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0003_tabledocument_file_or_url_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledocument',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
