# Generated by Django 5.1.4 on 2025-09-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0007_alter_tabledocument_document_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledocument',
            name='column_types',
            field=models.JSONField(blank=True, default=dict, help_text='A mapping of column names to their data types. This is used to enforce data types when displaying the table.'),
        ),
    ]
