# Generated by Django 5.1.4 on 2025-09-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0008_tabledocument_column_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledocument',
            name='column_options',
            field=models.JSONField(blank=True, default=dict, help_text='A mapping of column names to their visibility, editability, sortability and searchability for the final table presentation'),
        ),
    ]
