# Generated by Django 5.1.4 on 2025-09-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledocuments', '0009_tabledocument_column_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledocument',
            name='column_names',
            field=models.JSONField(blank=True, default=list, help_text='A mapping of the column names present in the document'),
        ),
    ]
